import Head from 'next/head'
import axios from 'axios'
import ButtonSecondary from '../components/buttons/ButtonSecondary'
import ButtonPrimary from '../components/buttons/ButtonPrimary'
import { Button, ChakraProvider } from '@chakra-ui/react'
import theme from '../utils/extendedTheme'
import "@fontsource/nunito"
import Navbar from '../components/layouts/Navbar'

export default function Home() {
  return (
    <ChakraProvider theme={theme}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-slate-100'>
        <Navbar />
        <h1 className="text-4xl font-bold">Bioskop Abah</h1>
        <p className='text-2xl font-semibold'>Tonton Sekarang</p>
        <div className="grid grid-cols-3 gap-5">
         <ButtonSecondary>
          Halo
         </ButtonSecondary>
         <ButtonPrimary>
          Halo Primary
         </ButtonPrimary>
         <Button>
          Halo
         </Button>
        </div>
      </main>
      <footer></footer>

    </ChakraProvider>
  )
}

// export async function getServerSideProps() {
//   // const result = await axios.get('https://api.themoviedb.org/3/movie/now_playing?api_key=4cee0d1f3d660d8d420266c93e1f1e5d&language=en-US&page=1');
//   // // const data = result.data.results
//   // return {
//   //   props: {
//   //     movies: data
//   //   }
//   // }
// }
