import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios'


export default function Home({ movies }) {
  console.log(movies)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-slate-100'>
        <h1 className="text-4xl font-bold">Bioskop Abah</h1>
        <p className='text-2xl font-semibold'>Tonton Sekarang</p>
        <div className="grid grid-cols-3 gap-5">
         
        </div>
      </main>
      <footer></footer>

    </div>
  )
}

// export async function getServerSideProps() {
//   // const result = await axios.get('https://api.themoviedb.org/3/movie/now_playing?api_key=4cee0d1f3d660d8d420266c93e1f1e5d&language=en-US&page=1');
//   // // const data = result.data.results
//   // return {
//   //   props: {
//   //     movies: data
//   //   }
//   // }
// }
